# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('SourceTexts', '0002_auto_20160709_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTextsIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='sourcetextsformpage',
            name='from_language',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='sourcetextsformpage',
            name='source_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sourcetextsformpage',
            name='to_language',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
