# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0003_auto_20160709_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetextsformpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourcetextsformpage',
            name='thank_you_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
