# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0004_auto_20160710_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetextsformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='SourceTexts.SourceTextsFormPage'),
        ),
    ]
