# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0005_auto_20160710_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcetextsformfield',
            name='page',
        ),
        migrations.RenameField(
            model_name='sourcetextsformpage',
            old_name='thank_you_text',
            new_name='submit_info',
        ),
        migrations.RemoveField(
            model_name='sourcetextsformpage',
            name='from_language',
        ),
        migrations.RemoveField(
            model_name='sourcetextsformpage',
            name='source_text',
        ),
        migrations.RemoveField(
            model_name='sourcetextsformpage',
            name='to_language',
        ),
        migrations.AddField(
            model_name='sourcetextsformpage',
            name='thanks_info',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SourceTextsFormField',
        ),
    ]
