# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0008_remove_sourcetextsformpage_thank_you_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcetextsformpage',
            name='intro',
        ),
    ]
