# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0009_remove_sourcetextsformpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetextsformpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
