# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0011_remove_sourcetextsformpage_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ST', models.CharField(max_length=200)),
                ('TL', models.CharField(max_length=200)),
                ('FL', models.CharField(max_length=200)),
            ],
        ),
    ]
