# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0013_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alignment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='frequency_list_exists',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='from_language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='to_language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='translation',
            field=models.TextField(null=True),
        ),
    ]
