# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('SourceTexts', '0016_knownlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('from_language', models.TextField(max_length=100, null=True)),
                ('to_language', models.TextField(max_length=100, null=True)),
                ('translation', models.TextField(null=True)),
                ('alignment', models.TextField(null=True)),
                ('frequency_list_exists', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DF',
        ),
        migrations.RemoveField(
            model_name='sourcetexts',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='sourcetextsformfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='sourcetextsformpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='sourcetextsindex',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='freqlist',
            name='postpk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SourceTexts.Source'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SourceTexts',
        ),
        migrations.DeleteModel(
            name='SourceTextsFormField',
        ),
        migrations.DeleteModel(
            name='SourceTextsFormPage',
        ),
        migrations.DeleteModel(
            name='SourceTextsIndex',
        ),
    ]
