# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0018_auto_20160720_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='freqlist',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
