# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SourceTexts', '0019_freqlist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freqlist',
            name='title',
        ),
    ]
